### PR TITLE
Demo data

### LINKED ISSUE #25: Mock data
Allow developers to use mock data so they don't have to run additional services

This would also help run regression tests on a CI service

MQTT messages could also be mocked in service workers. Example: https://googlechrome.github.io/samples/service-worker/mock-responses/service-worker.js

### PR DESCRIPTION
**Pull request by grgur**
Per #25, this PR enables mock config data for users who don't have docker installed and for testing in Continuous Integration.

Enable this feature by setting ENV variable `REACT_APP_DEMO` to `true` in `.env`. It watches for a string `true` and doesn't normalize to a boolean by design.

The DEMO environment can also mimic MQTT traffic and responds on _set_ with a delayed _status_.

I also exposed `SEND_MQTT_MESSAGE` function to `window` in case of `NODE_ENV=testing`. This could help test reactivity on mqtt traffic.

Note: MQTT will not connect in this case.

As a side effect, I noticed that subscriptions that are registered before the mqtt connection has been made will throw an exception. This PR includes a new feature that will queue up subscriptions that will be registered on a successful connection.

If a user unsubscribes before a connection has been made, the subscription item will be deleted from the queue. 

This PR also makes additional checks for a few services to ensure we have proper types in the config.  I intentionally renamed `Config` to `config` to match JavaScript naming patterns where pascalCase (aka UpperCamelCase) references a class, interface, or typedef; and camelCase (lowerCamelCase) references an instance, a method, local variables, etc.

Closes #25

### CODE REVIEW

File: src/App.js [hunk 1]
```diff
@@ -1,6 +1,6 @@
 import React, { Suspense, useState, useEffect, lazy } from "react";
-import ConfigurationContext from "@/hooks/contexts/ConfigurationContext";
 import MqttProvider from "@/providers/mqtt";
+import ConfigProvider from "@/providers/config";
```
Comment (mschwartz) [inline src/App.js]: We have hooks/
hooks/reducers
hooks/contexts

Why not hooks/providers?

File: src/Phone/Sensors/SensorsTab.js [hunk 2]
```diff
@@ -6,31 +6,35 @@ import MQTT from "@/lib/MQTT";
 import { Badge, Card } from "react-bootstrap";
 
 const SensorsTab = () => {
-  const Config = useConfig();
+  const config = useConfig();
```
Comment (mschwartz) [inline src/Phone/Sensors/SensorsTab.js]: Please leave Config as is

In some places in the code, we have ({ config }) passed in to configure a component.

And Config is, in theory, a CONSTANT.

File: src/Tablet/Autelis/Autelis.js [hunk 3]
```diff
@@ -10,6 +10,9 @@ const LOCALSTORAGE_KEY = "autelisTabletTabState";
 const Autelis = () => {
   const config = useConfig();
   const [activeTab, setActiveTab] = useState(localStorage.getItem(LOCALSTORAGE_KEY) || "0");
+
+  if (!config) return null;
```
Comment (mschwartz) [inline src/Tablet/Autelis/Autelis.js]: I prefer 

```
if (!config) {
  return null;
}
```

Makes it easy to add to the if clause or comment out.

If the code is supposed to look like one individual wrote it all (style-wise), this should be consistent, no?

File: src/Tablet/Sensors/SensorsTab.js [hunk 4]
```diff
@@ -12,10 +12,12 @@ import {
 import { Row, Col, Card } from "react-bootstrap";
 
 const SensorsTab = () => {
-  const Config = useConfig();
-  if (!Config) {
+  const config = useConfig();
```
Comment (mschwartz) [inline src/Tablet/Sensors/SensorsTab.js]: Config

File: src/App.js (hunk 1 above)
Comment (grgur) [reply src/App.js]: providers do different things. Hooks leverage provider context data, but don't have to work together. Also, we may want to change how we use hooks to avoid repeating conditions

Comment (mschwartz) [reply src/App.js]: Why should contexts be a subdirectories of hooks/ and providers not be?

It should be consistent, IMO.  If you want to move the others out of hooks, then it should be part of the PR, no?

File: src/Phone/Sensors/SensorsTab.js (hunk 2 above)
Comment (grgur) [reply src/Phone/Sensors/SensorsTab.js]: Let's not, please :) It's confusing me all the time. `config` or `CONFIG` should be fine.

Here's how Google standardizes it https://google.github.io/styleguide/jsguide.html. I'm not saying we need to follow Google, but it's just one of the documented style guides. It outlines the standards that are followed by the JS community

Comment (mschwartz) [reply src/Phone/Sensors/SensorsTab.js]: Using config is going to cause errors.

I guarantee it.

File: src/App.js (hunk 1 above)
Comment (grgur) [reply src/App.js]: There are no contexts anymore. It's consistent
